Proyecto Avellanas/MVCSolution/Avanzada/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Avanzada.Models.PatternRepository;
using Avanzada.ViewModel.CursoViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Avanzada.Controllers
{
    public class CursoController : Controller
    {
        private IRepositorioCurso repocurso;

        public CursoController()
        {
            repocurso = new Estructura();
        }

        public IActionResult Curso()
        {
            ViewBag.Title = "Cursos";

            return View(new CursoViewModel()
            {
                Title = "Cursos",
                Curso = repocurso.ObtenerCursos()
            });

        }

        public IActionResult Eliminar()
        {
            ViewBag.Title = "Eliminar Cursos";

            return View(new EliminarViewModel()
            {
                Title = "Eliminar Cursos",
                Curso = repocurso.ObtenerCursos()
            });

        }

        public IActionResult Editar()
        {
            ViewBag.Title = "Editar Cursos";

            return View(new EditarViewModel()
            {
                Title = "Editar Cursos",
                Curso = repocurso.ObtenerCursos()
            });

        }
    }
}

Proyecto Avellanas/MVCSolution/Avanzada/Controllers/GrupoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Avanzada.Models;
using Avanzada.Models.PatternRepository;
using Avanzada.ViewModel.GrupoViewModel;
using Microsoft.AspNetCore.Mvc;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Avanzada.Controllers
{
    public class GrupoController : Controller
    {
        IRepositorioGrupo repogrupo;

		public GrupoController(IRepositorioGrupo _repositorio)
		{
			repogrupo = _repositorio;
		}

		public GrupoController()
        {
            repogrupo = new Estructura();
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.Title = "Grupos";

            return View(new IndexViewModel()
            {
                Title = "Grupos",
                Grupo = repogrupo.ObtenerGrupo()
            });
            //return View(x.ObtenerPersonas());

        }

		IRepositorioGrupo repoGrupo;


		public IActionResult Eliminar()
		{
			EliminarViewModel modelo = new EliminarViewModel();
			modelo.Title = "Eliminar Grupo";
			return View(modelo);

		}

		[HttpPost]
		public IActionResult Eliminar(int id)
		{
			repoGrupo.EliminarGrupo(id);
			return RedirectToAction("Crear");
		}

		public IActionResult Editar()
		{

			EditarViewModel modelo = new EditarViewModel();
			modelo.Title = "Editar Grupo";

			return View(modelo);
		}


		[HttpPost]
		public IActionResult Editar(EditarViewModel modelo)
		{
			if (!ModelState.IsValid || repoGrupo.ExisteGrupo(modelo.GrupoId))
			{
				if (repoGrupo.ExisteGrupo(modelo.GrupoId))
				{
					modelo.ExisteGrupo = true;
				}

				return View(modelo);
			}
			repoGrupo.EditarGrupo(new Grupo()
			{
				GrupoId = modelo.GrupoId,
				Horario = modelo.Horario
			});

			return RedirectToAction("Crear");
		}




		public IActionResult Crear()
		{
			CrearViewModel modelo = new CrearViewModel();
			modelo.Title = "Crear Grupo";

			return View(modelo);
		}

		[HttpPost]
		public IActionResult Crear(CrearViewModel modelo)
		{
			if (!ModelState.IsValid)
			{
				if (repoGrupo.ExisteGrupo(modelo.GrupoId))
				{
					modelo.ExisteGrupo = true;
				}
				return View(modelo);
			}


			if (!repoGrupo.ExisteGrupo(modelo.GrupoId))
			{
				repoGrupo.CrearGrupo(new Grupo()
				{
					GrupoId = modelo.GrupoId,
					Horario = modelo.Horario
				});
			}

			return RedirectToAction("Crear");
		}

	}
}

Proyecto Avellanas/MVCSolution/Avanzada/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Avanzada.ViewModel.InicioViewModel;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Avanzada.Controllers
{
    public class InicioController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.Title = "Inicio";

            return View(new IndexViewModel()
            {
                Title = "Inicio",
            });
            //return View(x.ObtenerPersonas());

        }
    }
}

Proyecto Avellanas/MVCSolution/Avanzada/Controllers/NotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Avanzada.Models;
using Avanzada.Models.PatternRepository;
using Avanzada.ViewModel.NotaViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Avanzada.Controllers
{
    public class NotaController : Controller
    {
        IRepositorioNota repoNota; 

        public NotaController()
        {
            repoNota = new Estructura();
        }

        public IActionResult Ver()
        {
            ViewBag.Title = "Ver Notas";

            return View(new VerViewModel()
            {
                Title = "Ver Notas",
                Notas = repoNota.ObtenerNotas()
            });
        }

        public IActionResult Editar()
        {
            EditarViewModel modelo = new EditarViewModel();
            modelo.Title = "Editar Notas";
            
            return View(modelo);
        }

        public IActionResult Historico()
        {
            HistoricoViewModel modelo = new HistoricoViewModel();
            modelo.Title = "Historial Notas";
            return View(modelo);
        }
    }
}

Proyecto Avellanas/MVCSolution/Avanzada/Views/Inicio/Index.cshtml
@model Avanzada.ViewModel.InicioViewModel.IndexViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = Model.Title;

}

<head>

    <link rel="stylesheet" type="text/css" href="estilo_menu.css">
</head>

<header>

    <nav class="navbar navbar-toggleable-md navbar-inverse navbar-fixed-top bg-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <span class="fa fa-university"></span> Campus Virtual
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                                        <li class="active"><a asp-controller="Inicio" asp-action="Index">Inicio <span class="sr-only">(current)</span></a></li>


                    <li>
                        <a href="#" data-toggle="modal" data-target="#Asistencia"><span class="fa fa-question-circle"></span> Asistencia Tecnica</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a asp-controller="Perfil" asp-action="Ver"> <span class="fa fa-user"></span> Usuario</a>

                    @*<a href="Perfil.html">
                        <span class="fa fa-user"></span> Usuario
                    </a>*@
                    </li>
                    <li>
                        <a href="Login.html">
                            <span class="fa fa-sign-out"></span> Cerrar Sesion
                        </a>
                    </li>
                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</header>


<body>

    <br>
    <div class="buttons">

        <div class="container">

            <div class="row">


                <div class="col col-md-2">

                    <div class="btn-group btn-group-justified">
                        @*<a href="Matri.html" class="btn btn-primary">Matricula</a>*@
                        <a asp-controller="Matricula" asp-action="Index" class="btn btn-primary"> Matricula</a>
                      
                    </div>
                </div>

                <div class="col-md-2">

                    <div class="btn-group btn-group-justified">
                        <a asp-controller="Nota" asp-action="Ver" class="btn btn-primary">Notas Profesor</a>
                    </div>
                </div>

                <div class="col-md-2">

                    <div class="btn-group btn-group-justified">
                        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick="Label()">Marca Profesor</a>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="btn-group btn-group-justified">
                        @*<a href="Registro.html" class="btn btn-primary">Registro</a>*@
                        <a asp-controller="Persona" asp-action="Crear" class="btn btn-primary"> Registro</a>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="btn-group btn-group-justified">
                        <a href="Carrera.html" class="btn btn-primary">Carreras</a>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="btn-group btn-group-justified">
                        <a href="AulaLinea.html" class="btn btn-primary">Aula</a>
                    </div>
                </div>
            </div>
            <hr>

            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header text-center">

                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title w-100 font-weight-bold">Marcar Entrada y Salida</h4>
                        </div>
                        <div class="modal-body text-center mb-1">
                            <h5 class="text-align-center" id="lbl_date">Fecha</h5>
                            <label class="text-align-center" id="lbl_time">00::00::00</label>
                            <div class="text-center mt-4">
                                <button type="button" class="btn btn-success">Marcar Entrada</button>
                                <button type="button" class="btn btn-danger">Marcar Salida</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">

                <div class="col col-md-2">

                    <div class="btn-group btn-group-justified">
                        <a href="Permisos.html" class="btn btn-primary">Permisos</a>
                    </div>
                </div>

                <div class="col-md-2">

                    <div class="btn-group btn-group-justified">
                        <a asp-controller="Nota" asp-action="Historico" class="btn btn-primary">Notas Estudiante</a>
                    </div>
                </div>

                <div class="col-md-2">

                    <div class="btn-group btn-group-justified">
                        <a asp-controller="Asistencia_Estudiante" asp-action="Asistencia_Estudiante" class="btn btn-primary"> Asistencia Estudiante</a>
                    </div>
                </div>

                <div class="col-md-2">

                    <div class="btn-group btn-group-justified">
                        <a asp-controller="Curso" asp-action="Curso" class="btn btn-primary">  Curso</a>
                    </div>
                </div>

                <div class="col-md-2">

                    <div class="btn-group btn-group-justified">
                        <a asp-controller="Grupo" asp-action="Index" class="btn btn-primary">  Grupo</a>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="btn-group btn-group-justified">
                       
                        <a asp-controller="Rubros" asp-action="Index" class="btn btn-primary"> Rubros</a>
                    </div>
                </div>


            </div>



        </div>

    </div>

    <br />
    <br />

    <div class="container">

        <div class="row">

            <div class="col-md-2 col-md-offset-2">

                <!--	Begins Carrusel -->
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!--  Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                    </ol>

                    <div class="carousel-inner">
                        <div class="item active">
                            <img src="http://www.massey.ac.nz/massey/fms/campuses/images/auckland-campus1.jpg?29FF999425040D0915A4B70C364DFAB1" alt="Los Angeles" style="width:100%;">
                        </div>

                        <div class="item">
                            <img src="http://greatruns.com/wp-content/uploads/2017/03/OSU-Oval-700x400.jpeg" alt="Chicago" style="width:100%;">
                        </div>

                        <div class="item">
                            <img src="http://www.aalto.fi/fi/about/campus/havainnekuva.jpg" alt="New york" style="width:100%;">
                        </div>
                    </div>

                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

        </div>
    </div>



    <!--ends Carrusel-->



</body>