Proyecto Avellanas/MVCSolution/Avanzada/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Avanzada.Models
{
    public class Persona
    {
        public int PersonaId { get; set; }
        public string Nombre{ get; set; }
        public string Apellido{ get; set; }
        public string Telefono{ get; set; }
        public int Cedula{ get; set; }
        public int Carne { get; set; }
        public DateTime FechaNacimiento{ get; set; }
        public string Correo{ get; set; }
        public int  Sexo{ get; set; }        
        public string Usuario{ get; set; }
        public string Contraseña{ get; set; }
        public virtual ICollection<TipoPersona> TipoPersonaId { get; set; }= new List<TipoPersona>();
        //una persona puede tener muchas carreras asociadas
        public virtual ICollection<Carreras> CarrerasId { get; set; }= new List<Carreras>();
        public virtual ICollection<Notas> Notas { get; set; }= new List<Notas>();

        public virtual ICollection<Asistencia_Estudiante> Asistencia_Estudiante { get; set; } = new List<Asistencia_Estudiante>();
        public virtual ICollection<Asistencia_Profesor> Asistencia_Profesor { get; set; } = new List<Asistencia_Profesor>();
        //public Login InicioSesion { get; set; }

        public ICollection<Matricula> Matriculas { get; set; } = new List<Matricula>();

    }
}

Proyecto Avellanas/MVCSolution/Avanzada/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Avanzada.Models;
using Avanzada.Models.PatternRepository;
using Avanzada.ViewModel.PersonaViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Avanzada.Controllers
{

    public class PersonaController : Controller
    {

        IRepositorioPersona repopersona;

        public PersonaController(IRepositorioPersona _repositorio)
        {
            repopersona = _repositorio;
        }



        public IActionResult Eliminar()
        {
            EliminarViewModel modelo = new EliminarViewModel();
            modelo.Title = "Eliminar Persona";
            return View(modelo);

            //EliminarViewModel modelo = new EliminarViewModel();
            //modelo.Title = "Eliminar Persona";
            //modelo.Sexo = new List<SelectListItem>();
            //foreach (var valor in Enum.GetValues(typeof(Persona.Sexualidad)))
            //{
            //    modelo.Sexo.Add(new SelectListItem
            //    {
            //        Value = valor.ToString(),
            //        Text = Enum.GetName(typeof(Persona.Sexualidad), valor)
            //    });
            //}
            //return View(modelo);
        }

        [HttpPost]
        public IActionResult Eliminar(int id)
        {
            repopersona.EliminarPersona(id);
            return RedirectToAction("Crear");
        }

        //[HttpPost]
        //public IActionResult Eliminar(EliminarViewModel modelo)
        //{
        //    if (!ModelState.IsValid || repopersona.ExistePersona(modelo.Cedula))
        //    {
        //        if (repopersona.ExistePersona(modelo.Cedula))
        //        {
        //            modelo.ExistePersona = true;
        //        }
        //        modelo.Sexo = new List<SelectListItem>();
        //        foreach (var valor in Enum.GetValues(typeof(Persona.Sexualidad)))
        //        {
        //            modelo.Sexo.Add(new SelectListItem
        //            {
        //                Value = valor.ToString(),
        //                Text = Enum.GetName(typeof(Persona.Sexualidad), valor)
        //            });
        //        }
        //        return View(modelo);
        //    }
        //    repopersona.EliminarPersona(
        //        modelo.Carne);

        //    return RedirectToAction("Crear");
        //}



        public IActionResult Editar()
        {

            EditarViewModel modelo = new EditarViewModel();
            modelo.Title = "Editar Persona";
            //modelo.Sexo = new List<SelectListItem>();
            //foreach (var valor in Enum.GetValues(typeof(Persona.Sexualidad)))
            //{
            //    modelo.Sexo.Add(new SelectListItem
            //    {
            //        Value = valor.ToString(),
            //        Text = Enum.GetName(typeof(Persona.Sexualidad), valor)
            //    });
            //}
            return View(modelo);
        }


        [HttpPost]
        public IActionResult Editar(EditarViewModel modelo)
        {
            if (!ModelState.IsValid || repopersona.ExistePersona(modelo.Cedula))
            {
                if (repopersona.ExistePersona(modelo.Cedula))
                {
                    modelo.ExistePersona = true;
                }
                //modelo.Sexo = new List<SelectListItem>();
                //foreach (var valor in Enum.GetValues(typeof(Persona.Sexualidad)))
                //{
                //    modelo.Sexo.Add(new SelectListItem
                //    {
                //        Value = valor.ToString(),
                //        Text = Enum.GetName(typeof(Persona.Sexualidad), valor)
                //    });
                //}
                return View(modelo);
            }
            repopersona.EditarPersona(new Persona()
            {
                Apellido = modelo.Apellido,
                Nombre = modelo.Nombre,
                Carne = modelo.Carne,
                Cedula = modelo.Cedula,
                Correo = modelo.Correo,
                FechaNacimiento = modelo.FechaNacimiento,
                Telefono = modelo.Telefono,
                Usuario = modelo.Nombre + modelo.Apellido + "2",
                Contraseña = "123456",
                Sexo = repopersona.ObtenerSexo(modelo.Sexo)
            });

            return RedirectToAction("Crear");
        }




        public IActionResult Crear()
        {
            CrearViewModel modelo = new CrearViewModel();
            modelo.Title = "Crear Persona";
            //modelo.Sexo = new List<SelectListItem>();
            //foreach (var valor in Enum.GetValues(typeof(Persona.Sexualidad)))
            //{
            //    modelo.Sexo.Add(new SelectListItem
            //    {
            //        Value = valor.ToString(),
            //        Text = Enum.GetName(typeof(Persona.Sexualidad), valor)
            //    });
            //}
            return View(modelo);
        }

        [HttpPost]
        public IActionResult Crear(CrearViewModel modelo)
        {
            if (!ModelState.IsValid)
            {
                if (repopersona.ExistePersona(modelo.Cedula))
                {
                    modelo.ExistePersona = true;
                }
                //modelo.Sexo = new List<SelectListItem>();
                //foreach (var valor in Enum.GetValues(typeof(Persona.Sexualidad)))
                //{
                //    modelo.Sexo.Add(new SelectListItem
                //    {
                //        Value = valor.ToString(),
                //        Text = Enum.GetName(typeof(Persona.Sexualidad), valor)
                //    });
                //}
                return View(modelo);
            }


            if (!repopersona.ExistePersona(modelo.Cedula))
            {
                repopersona.CrearPersona(new Persona()
                {
                    Apellido = modelo.Apellido,
                    Nombre = modelo.Nombre,
                    Carne = modelo.Carne,
                    Cedula = modelo.Cedula,
                    Correo = modelo.Correo,
                    FechaNacimiento = modelo.FechaNacimiento,
                    Telefono = modelo.Telefono,
                    Usuario = modelo.Nombre + "." + modelo.Apellido,
                    Contraseña = "123456",
                    Sexo = repopersona.ObtenerSexo(modelo.Sexo)
                });
            }

            return RedirectToAction("Crear");
        }





    }
}

Proyecto Avellanas/MVCSolution/Avanzada/Views/Persona/Crear.cshtml
@model Avanzada.ViewModel.PersonaViewModel.CrearViewModel
@{
    Layout = "~/Views/Shared/_layout.cshtml";
    ViewBag.Title = Model.Title;
}


<header>

    <nav class="navbar navbar-toggleable-md navbar-inverse navbar-fixed-top bg-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span class="fa fa-user"></span> Persona</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a asp-controller="Inicio" asp-action="Index">Inicio <span class="sr-only">(current)</span></a></li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Registro <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Persona" asp-action="Crear">Agregar</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a asp-controller="Persona" asp-action="Editar">Editar</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a asp-controller="Persona" asp-action="Eliminar">Eliminar</a></li>

                        </ul>
                    </li>
                    <li><a href="#" data-toggle="modal" data-target="#Asistencia">Asistencia Tecnica</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>


</header>

<body class="body_registro">

    <section class="color_label_registro">

        <div class="container">

            <h3 class="titulos">@ViewBag.Title</h3>
            <hr>
        </div>

        <div id="wrapper" class="container">

            <form method="post" action="/Persona/Crear/">

                <fieldset>

                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label" asp-for="Nombre">Nombre</label>
                            <input asp-for="Nombre" class="form-control" placeholder="Jon" type="text">
                            <span asp-validation-for="Nombre"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label" asp-for="Apellido">Apellido</label>
                            <input asp-for="Apellido" class="form-control" placeholder="Doe" type="text">
                            <span asp-validation-for="Apellido"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label" asp-for="Telefono">Telefono</label>
                            <div class="input-group">
                                <span class="input-group-addon">+506</span>
                                <input asp-for="Telefono" class="form-control" placeholder="12345678" type="number">
                            </div>
                            <span asp-validation-for="Telefono"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label" asp-for="Cedula">Cedula</label>
                            <div class="input-group">
                                <span class="input-group-addon">ID</span>
                                <input asp-for="Cedula" class="form-control" placeholder="000000000" type="number">

                            </div>
                            <span asp-validation-for="Cedula"></span>
                        </div>
                    </div>




                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label" asp-for="Carne">Carne</label>
                            <input asp-for="Carne" class="form-control" placeholder="201801110256" type="number">
                            <span asp-validation-for="Carne"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label" asp-for="FechaNacimiento">Fecha nacimiento</label>
                            <input type="date" asp-for="FechaNacimiento" class="form-control">
                            <span asp-validation-for="FechaNacimiento"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label" asp-for="Correo">Correo</label>
                            <input asp-for="Correo" class="form-control" placeholder="ejemplo@org.com" type="email">
                            <span asp-validation-for="Correo"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label" asp-for="Sexo">Sexo</label>
                            <select asp-for="Sexo" class="form-control">
                                <option>Masculino</option>
                                <option>Femenino</option>
                                <option>Indefinido</option>

                            </select>
                            <span asp-validation-for="Sexo"></span>
                        </div>
                    </div>


                    @*<div class="form-group">
                            <div class="col-md-6">
                                <label class="control-label" asp-for="Usuario">Usuario</label>
                                <input asp-for="Usuario" class="form-control" placeholder="Usuario" type="text" disabled>
                                <span asp-validation-for="Usuario"></span>
                            </div>
                        </div>*@

                </fieldset>

                <button type="submit" class="btn btn-dark btn-lg btn_registrar">Registrar <span class="fa fa-save" aria-hidden="true"></span></button>
            </form>
        </div>
    </section>
</body>